- name: PlayBook 1 - Nginx Installation
  hosts: Nginx-Servers
  become: true
  tasks:
    - name: Install Nginx Web Server
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Start and Enable Nginx Service
      service:
        name: nginx
        state: started
        enabled: yes

- name: PlayBook 2 - MySQL Setup
  hosts: Database-Servers
  become: true
  tasks:
    - name: Install MySQL and Dependencies
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - mysql-server
        - mysql-client
        - python3-mysqldb
        - libmysqlclient-dev

    - name: Start and Enable MySQL Service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create MySQL User
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        priv: '*.*:ALL'
        host: '%'
        state: present

    - name: Create Database
      mysql_db:
        name: "{{ db_name }}"
        state: present

    - name: Enable Remote Login to MySQL
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: yes
      notify:
        - Restart MySQL

  handlers:
    - name: Restart MySQL
      service:
        name: mysql
        state: restarted

- name: PlayBook 3 - Apache Setup
  hosts: Apache-Servers
  become: true
  tasks:
    - name: Install Apache Web Server
      apt:
        name: apache2
        state: latest
        update_cache: yes

    - name: Start and Enable Apache Service
      service:
        name: apache2
        state: started
        enabled: yes
      notify: Restart Apache

    - name: Create Document Root for Virtual Host
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copy Index File
      template:
        src: "files/index-template.html"
        dest: "/var/www/{{ http_host }}/index.html"

    - name: Set Up Virtual Host Configuration
      template:
        src: "files/apache-template.conf"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"

    - name: Enable Site
      command: a2ensite {{ http_conf }}
      notify: Restart Apache

    - name: Allow HTTP Traffic on Port {{ http_port }}
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
